### ISSUE TITLE
Reactive zoom bug

### ISSUE THREAD

**Issue by brettviren** [BNLIF/edg-web#3] opened 2021-07-15 14:54 UTC
Not a big thing but I notice there is a range of zoom that will cause the LHS part of the home page to become inaccessible.  Zoom a little more and it "pops" into cell phone mode and becomes one scrollable screen.  Zoom out and enough of the LHS becomes visible.

**Comment by czczc** [comment] 2021-07-15 20:08
I would call this a "feature" not a bug. It's sometimes called "responsive web design" so that the web page is mobile friendly and the grid system automatically changes to fewer columns when the screen size is small. This behavior also happens when you resize the window.  

I think this page uses the bootstrap css framework, which handles this behavior automatically 
https://www.tutorialrepublic.com/twitter-bootstrap-tutorial/bootstrap-responsive-layout.php

**Comment by czczc** [comment] 2021-07-16 15:41
I misunderstood the original issue from @brettviren . The left-hand sidebar doesn't scroll, so if the window height is smaller than the sidebar content, the overflow content is hidden and inaccessible. 

This issue should be fixed in 84017ff by changing the sidebar css position from "fixed" to "sticky". It should now scroll together with the right-hand content and be always visible.

**Closed as completed by czczc** 2021-07-16 15:41 UTC
